### ISSUE TITLE
Opdrachtje

### ISSUE THREAD

**Issue by VandenAbbeeleBram** [EilishVanDerSnickt/MI2#1]
@EilishVanDerSnickt 

Opgave:

Maak een webpagina met een knop en een vierkant (zwart, 50px bij 50px)
Bij het laden van de pagina is het vierkant verborgen.
Als je op de knop klikt wordt het vierkant zichtbaar, en verplaatst hij zich in de vorm van een vierkant.
Na deze animatie komt het vierkant weer op zijn oorspronkelijke plaats terecht, en verdwijnt hij weer tot er weer op de knop geklikt wordt.

Succes!
Bram Van den Abbeele

**Comment by ophalvens** [comment]
@VandenAbbeeleBram kan je nakijken of de opdracht gemaakt is zoals je verwachtte? Als dat het geval is, kan dit issue afgesloten worden.

**Comment by VandenAbbeeleBram** [comment]
@EilishVanDerSnickt  Goed werk! Opdracht volbracht.
